<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xNAfIf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xNAfIf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xNAfIf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xNAfIf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6xNAfIf\App_KernelDevDebugContainer([
    'container.build_hash' => '6xNAfIf',
    'container.build_id' => '9f7f31e4',
    'container.build_time' => 1760133525,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xNAfIf');
