<?php

namespace Container1nNMttG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_66Fkr_GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.66Fkr.g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.66Fkr.g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'model' => ['privates', '.errored..service_locator.66Fkr.g.App\\Entity\\Model', NULL, 'Cannot autowire service ".service_locator.66Fkr.g": it needs an instance of "App\\Entity\\Model" but this type has been excluded in "config/services.yaml".'],
        ], [
            'model' => 'App\\Entity\\Model',
        ]);
    }
}
