<?php

namespace Container1nNMttG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NIoUSxSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NIoUSxS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NIoUSxS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'model' => ['privates', '.errored..service_locator.NIoUSxS.App\\Entity\\Model', NULL, 'Cannot autowire service ".service_locator.NIoUSxS": it needs an instance of "App\\Entity\\Model" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'model' => 'App\\Entity\\Model',
        ]);
    }
}
