<?php

namespace Container1nNMttG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TDBoxoYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tDBoxoY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tDBoxoY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vault' => ['privates', '.errored..service_locator.tDBoxoY.App\\Entity\\Vault', NULL, 'Cannot autowire service ".service_locator.tDBoxoY": it needs an instance of "App\\Entity\\Vault" but this type has been excluded in "config/services.yaml".'],
        ], [
            'vault' => 'App\\Entity\\Vault',
        ]);
    }
}
