<?php

namespace Container1nNMttG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P7J1106Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P7J1106' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P7J1106'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vaultRepository' => ['privates', 'App\\Repository\\VaultRepository', 'getVaultRepositoryService', true],
        ], [
            'vaultRepository' => 'App\\Repository\\VaultRepository',
        ]);
    }
}
