<?php

namespace Container1nNMttG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVault2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tDBoxoY.App\Entity\Vault' shared service.
     *
     * @return \App\Entity\Vault
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tDBoxoY": it needs an instance of "App\\Entity\\Vault" but this type has been excluded in "config/services.yaml".');
    }
}
