<?php

namespace Container6xNAfIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X01u0RjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x01u0Rj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x01u0Rj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ModelController::delete' => ['privates', '.service_locator.NIoUSxS', 'get_ServiceLocator_NIoUSxSService', true],
            'App\\Controller\\ModelController::edit' => ['privates', '.service_locator.NIoUSxS', 'get_ServiceLocator_NIoUSxSService', true],
            'App\\Controller\\ModelController::index' => ['privates', '.service_locator.66JIssR', 'get_ServiceLocator_66JIssRService', true],
            'App\\Controller\\ModelController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModelController::show' => ['privates', '.service_locator.66Fkr.g', 'get_ServiceLocator_66Fkr_GService', true],
            'App\\Controller\\VaultController::delete' => ['privates', '.service_locator.kojaURs', 'get_ServiceLocator_KojaURsService', true],
            'App\\Controller\\VaultController::edit' => ['privates', '.service_locator.kojaURs', 'get_ServiceLocator_KojaURsService', true],
            'App\\Controller\\VaultController::index' => ['privates', '.service_locator.P7J1106', 'get_ServiceLocator_P7J1106Service', true],
            'App\\Controller\\VaultController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VaultController::show' => ['privates', '.service_locator.tDBoxoY', 'get_ServiceLocator_TDBoxoYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ModelController:delete' => ['privates', '.service_locator.NIoUSxS', 'get_ServiceLocator_NIoUSxSService', true],
            'App\\Controller\\ModelController:edit' => ['privates', '.service_locator.NIoUSxS', 'get_ServiceLocator_NIoUSxSService', true],
            'App\\Controller\\ModelController:index' => ['privates', '.service_locator.66JIssR', 'get_ServiceLocator_66JIssRService', true],
            'App\\Controller\\ModelController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModelController:show' => ['privates', '.service_locator.66Fkr.g', 'get_ServiceLocator_66Fkr_GService', true],
            'App\\Controller\\VaultController:delete' => ['privates', '.service_locator.kojaURs', 'get_ServiceLocator_KojaURsService', true],
            'App\\Controller\\VaultController:edit' => ['privates', '.service_locator.kojaURs', 'get_ServiceLocator_KojaURsService', true],
            'App\\Controller\\VaultController:index' => ['privates', '.service_locator.P7J1106', 'get_ServiceLocator_P7J1106Service', true],
            'App\\Controller\\VaultController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VaultController:show' => ['privates', '.service_locator.tDBoxoY', 'get_ServiceLocator_TDBoxoYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ModelController::delete' => '?',
            'App\\Controller\\ModelController::edit' => '?',
            'App\\Controller\\ModelController::index' => '?',
            'App\\Controller\\ModelController::new' => '?',
            'App\\Controller\\ModelController::show' => '?',
            'App\\Controller\\VaultController::delete' => '?',
            'App\\Controller\\VaultController::edit' => '?',
            'App\\Controller\\VaultController::index' => '?',
            'App\\Controller\\VaultController::new' => '?',
            'App\\Controller\\VaultController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ModelController:delete' => '?',
            'App\\Controller\\ModelController:edit' => '?',
            'App\\Controller\\ModelController:index' => '?',
            'App\\Controller\\ModelController:new' => '?',
            'App\\Controller\\ModelController:show' => '?',
            'App\\Controller\\VaultController:delete' => '?',
            'App\\Controller\\VaultController:edit' => '?',
            'App\\Controller\\VaultController:index' => '?',
            'App\\Controller\\VaultController:new' => '?',
            'App\\Controller\\VaultController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
