<?php

namespace Container6xNAfIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NIoUSxS.App\Entity\Model' shared service.
     *
     * @return \App\Entity\Model
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NIoUSxS": it needs an instance of "App\\Entity\\Model" but this type has been excluded in "config/services.yaml".');
    }
}
